"""updated models for document

Revision ID: bbfd9ea70e5b
Revises: 4888f9453d13
Create Date: 2025-12-28 15:30:11.878477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbfd9ea70e5b'
down_revision: Union[str, Sequence[str], None] = '4888f9453d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'total_chunks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=False)
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'total_chunks',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
